In [1]:
! pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip 

     |████████████████████████████████| 25.9 MB 1.6 MB/s 
     |████████████████████████████████| 10.9 MB 5.2 MB/s 
     |████████████████████████████████| 596 kB 60.6 MB/s 
     |████████████████████████████████| 102 kB 10.7 MB/s 
     |████████████████████████████████| 690 kB 51.5 MB/s 
     |████████████████████████████████| 4.7 MB 36.5 MB/s 
     |████████████████████████████████| 63 kB 1.5 MB/s 
     |████████████████████████████████| 812 kB 71.2 MB/s 
     |████████████████████████████████| 38.1 MB 1.5 MB/s 
  Created wheel for pandas-profiling: filename=pandas_profiling-3.1.1-py2.py3-none-any.whl size=261287 sha256=1fea04e8ac13cb8c4dd4272f7ebc15fd3500e53773ca1da2c3d03205cb481f5f
  Stored in directory: /tmp/pip-ephem-wheel-cache-_6a6mxoh/wheels/cc/d5/09/083fb07c9363a2f45854b0e3a7de7d7c560f07da74b9e9769d
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27098 sha256=e13eb23bfd4141e23edd89fd284753459f441322e0205514bf04c7292c038da6
  Stored in directory: /ro

In [2]:
from pandas_profiling import ProfileReport

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("greenhouse.csv")

In [5]:
df.head()

temp1  temp2  temp3  humidity1  humidity2  humidity3     light  Blower  \
0   27.3   29.2   28.3       91.8         85         95  18414.20       1   
1   27.5   29.1   28.7       95.5         86         95  11324.60       1   
2   27.6   29.3   28.7       95.6         86         95  18218.30       1   
3   27.7   29.3   28.9       96.0         85         95   9532.92       1   
4   27.7   29.3   28.9       95.5         85         95   9432.08       1   

   Mister  
0       1  
1       1  
2       1  
3       1  
4       1

In [6]:
df_first_10 = df.iloc[:10]
print(df_first_10)

   temp1  temp2  temp3  humidity1  humidity2  humidity3     light  Blower  \
0   27.3   29.2   28.3       91.8         85         95  18414.20       1   
1   27.5   29.1   28.7       95.5         86         95  11324.60       1   
2   27.6   29.3   28.7       95.6         86         95  18218.30       1   
3   27.7   29.3   28.9       96.0         85         95   9532.92       1   
4   27.7   29.3   28.9       95.5         85         95   9432.08       1   
5   27.7   29.3   28.8       94.8         86         95   7251.25       1   
6   27.6   29.2   28.8       94.6         83         95   6826.67       1   
7   27.6   28.9   28.7       94.6         81         95   6709.17       1   
8   27.6   28.9   28.6       88.3         83         95   6669.17       1   
9   27.7   28.8   28.5       86.6         84         95   7050.00       1   

   Mister  
0       1  
1       1  
2       1  
3       1  
4       1  
5       1  
6       1  
7       1  
8       1  
9       1  


In [7]:
#Pandas analysis
prof = ProfileReport(df)
prof.to_file(output_file='greenhouse.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [11]:
import numpy as np

**Random Forest**

In [15]:
#Random forest for blower prediction

X=df.drop(['Blower','Mister'], axis=1)
y=df['Blower']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X,y,test_size=0.3,random_state=1)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(x_train)
x_train = pd.DataFrame(X_train)
X_test = scaler.transform(x_test)
x_test = pd.DataFrame(X_test)

#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

# Train the model on training data
clf.fit(x_train, y_train);

# Use the forest's predict method on the test data
y_pred = clf.predict(x_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# confusion matrix in sklearn
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# confusion matrix
matrix = confusion_matrix(y_test,y_pred, labels=[1,0])
print('\nConfusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(y_test,y_pred,labels=[1,0]).reshape(-1)
print('\nOutcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(y_test,y_pred,labels=[1,0])
print('\nClassification report : \n',matrix)

Accuracy: 0.9925205684367988

Confusion matrix : 
 [[1434    7]
 [  13 1220]]

Outcome values : 
 1434 7 13 1220

Classification report : 
               precision    recall  f1-score   support

           1       0.99      1.00      0.99      1441
           0       0.99      0.99      0.99      1233

    accuracy                           0.99      2674
   macro avg       0.99      0.99      0.99      2674
weighted avg       0.99      0.99      0.99      2674



In [16]:
#Random forest for mister prediction

X=df.drop(['Blower','Mister'], axis=1)
y=df['Mister']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X,y,test_size=0.3,random_state=1)


from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(x_train)
x_train = pd.DataFrame(X_train)
X_test = scaler.transform(x_test)
x_test = pd.DataFrame(X_test)

#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

# Train the model on training data
clf.fit(x_train, y_train);

# Use the forest's predict method on the test data
y_pred = clf.predict(x_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# confusion matrix in sklearn
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# confusion matrix
matrix = confusion_matrix(y_test,y_pred, labels=[1,0])
print('\nConfusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(y_test,y_pred,labels=[1,0]).reshape(-1)
print('\nOutcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(y_test,y_pred,labels=[1,0])
print('\nClassification report : \n',matrix)

Accuracy: 0.9869109947643979

Confusion matrix : 
 [[1311   16]
 [  19 1328]]

Outcome values : 
 1311 16 19 1328

Classification report : 
               precision    recall  f1-score   support

           1       0.99      0.99      0.99      1327
           0       0.99      0.99      0.99      1347

    accuracy                           0.99      2674
   macro avg       0.99      0.99      0.99      2674
weighted avg       0.99      0.99      0.99      2674



**Logistic Regression**

In [17]:
#Logistic regression for blower prediction

X=df.drop(['Blower','Mister'], axis=1)
y=df['Blower']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X,y,test_size=0.3,random_state=1)


from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(x_train)
x_train = pd.DataFrame(X_train)
X_test = scaler.transform(x_test)
x_test = pd.DataFrame(X_test)

#Import LogisticRegression Model
from sklearn.linear_model import LogisticRegression

# all parameters not specified are set to their defaults
logisticRegr = LogisticRegression()

# Train the model on training data
logisticRegr.fit(x_train, y_train)

# Use the LogisticRegression Model on the test data
y_pred = logisticRegr.predict(x_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# confusion matrix in sklearn
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# confusion matrix
matrix = confusion_matrix(y_test,y_pred, labels=[1,0])
print('\nConfusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(y_test,y_pred,labels=[1,0]).reshape(-1)
print('\nOutcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(y_test,y_pred,labels=[1,0])
print('\nClassification report : \n',matrix)

Accuracy: 0.9584891548242334

Confusion matrix : 
 [[1409   32]
 [  79 1154]]

Outcome values : 
 1409 32 79 1154

Classification report : 
               precision    recall  f1-score   support

           1       0.95      0.98      0.96      1441
           0       0.97      0.94      0.95      1233

    accuracy                           0.96      2674
   macro avg       0.96      0.96      0.96      2674
weighted avg       0.96      0.96      0.96      2674



In [18]:
#Logistic regression for mister prediction

X=df.drop(['Blower','Mister'], axis=1)
y=df['Mister']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X,y,test_size=0.3,random_state=1)


from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(x_train)
x_train = pd.DataFrame(X_train)
X_test = scaler.transform(x_test)
x_test = pd.DataFrame(X_test)

#Import LogisticRegression Model
from sklearn.linear_model import LogisticRegression

# all parameters not specified are set to their defaults
logisticRegr = LogisticRegression()

# Train the model on training data
logisticRegr.fit(x_train, y_train)

# Use the LogisticRegression Model on the test data
y_pred = logisticRegr.predict(x_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# confusion matrix in sklearn
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# confusion matrix
matrix = confusion_matrix(y_test,y_pred, labels=[1,0])
print('\nConfusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(y_test,y_pred,labels=[1,0]).reshape(-1)
print('\nOutcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(y_test,y_pred,labels=[1,0])
print('\nClassification report : \n',matrix)

Accuracy: 0.9450261780104712

Confusion matrix : 
 [[1281   46]
 [ 101 1246]]

Outcome values : 
 1281 46 101 1246

Classification report : 
               precision    recall  f1-score   support

           1       0.93      0.97      0.95      1327
           0       0.96      0.93      0.94      1347

    accuracy                           0.95      2674
   macro avg       0.95      0.95      0.95      2674
weighted avg       0.95      0.95      0.95      2674



**K–Nearest Neighbor(KNN)**

In [19]:
#Knn for blower prediction

X=df.drop(['Blower','Mister'], axis=1)
y=df['Blower']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X,y,test_size=0.3,random_state=1)


from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(x_train)
x_train = pd.DataFrame(X_train)
X_test = scaler.transform(x_test)
x_test = pd.DataFrame(X_test)

#Import KNeighborsClassifier Model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

# Train the model on training data
classifier.fit(x_train, y_train)

# Use the Model on the test data
y_pred = classifier.predict(x_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# confusion matrix in sklearn
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# confusion matrix
matrix = confusion_matrix(y_test,y_pred, labels=[1,0])
print('\nConfusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(y_test,y_pred,labels=[1,0]).reshape(-1)
print('\nOutcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(y_test,y_pred,labels=[1,0])
print('\nClassification report : \n',matrix)

Accuracy: 0.9891548242333582

Confusion matrix : 
 [[1430   11]
 [  18 1215]]

Outcome values : 
 1430 11 18 1215

Classification report : 
               precision    recall  f1-score   support

           1       0.99      0.99      0.99      1441
           0       0.99      0.99      0.99      1233

    accuracy                           0.99      2674
   macro avg       0.99      0.99      0.99      2674
weighted avg       0.99      0.99      0.99      2674



In [20]:
#Knn for mister prediction

X=df.drop(['Blower','Mister'], axis=1)
y=df['Mister']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X,y,test_size=0.3,random_state=1)


from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(x_train)
x_train = pd.DataFrame(X_train)
X_test = scaler.transform(x_test)
x_test = pd.DataFrame(X_test)

#Import KNeighborsClassifier Model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

# Train the model on training data
classifier.fit(x_train, y_train)

# Use the Model on the test data
y_pred = classifier.predict(x_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# confusion matrix in sklearn
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# confusion matrix
matrix = confusion_matrix(y_test,y_pred, labels=[1,0])
print('\nConfusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(y_test,y_pred,labels=[1,0]).reshape(-1)
print('\nOutcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(y_test,y_pred,labels=[1,0])
print('\nClassification report : \n',matrix)

Accuracy: 0.9857890800299177

Confusion matrix : 
 [[1308   19]
 [  19 1328]]

Outcome values : 
 1308 19 19 1328

Classification report : 
               precision    recall  f1-score   support

           1       0.99      0.99      0.99      1327
           0       0.99      0.99      0.99      1347

    accuracy                           0.99      2674
   macro avg       0.99      0.99      0.99      2674
weighted avg       0.99      0.99      0.99      2674

